{% set name = "flask-themes2" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/Flask-Themes2-{{ version }}.tar.gz
  sha256: 82c3204105e38437d04619bb1f4901cbc8cac5def9598f8f84747a464fcf50fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - flask >=2.0
    - python >={{ python_min }}

test:
  imports:
    - flask_themes2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sysr-q/flask-themes2
  summary: Provides infrastructure for theming Flask applications
  license: MIT
  license_file: LICENSE
  description: |
    Flask-Themes2 is a fork of Spirits, which is in turn a fork of Flask-Themes.
  doc_url: https://flask-themes2.readthedocs.io
  dev_url: https://github.com/sysr-q/flask-themes2

extra:
  recipe-maintainers:
    - HeavyTony2
